-- begin CARSCUBAPLATFORM_COUNTRY
create unique index IDX_CARSCUBAPLATFORM_COUNTRY_UNIQ_NAME on CARSCUBAPLATFORM_COUNTRY (NAME)^
-- end CARSCUBAPLATFORM_COUNTRY
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_COUNTRY foreign key (COUNTRY_ID) references CARSCUBAPLATFORM_COUNTRY(ID)^
create index IDX_SEC_USER_ON_COUNTRY on SEC_USER (COUNTRY_ID)^
-- end SEC_USER
-- begin CARSCUBAPLATFORM_AUTO_PRODUCER
alter table CARSCUBAPLATFORM_AUTO_PRODUCER add constraint FK_CARSCUBAPLATFORM_AUTO_PRODUCER_ON_COUNTRY foreign key (COUNTRY_ID) references CARSCUBAPLATFORM_COUNTRY(ID)^
create unique index IDX_CARSCUBAPLATFORM_AUTO_PRODUCER_UNIQ_NAME on CARSCUBAPLATFORM_AUTO_PRODUCER (NAME)^
create unique index IDX_CARSCUBAPLATFORM_AUTO_PRODUCER_UNIQ_PRODUCER_CODE on CARSCUBAPLATFORM_AUTO_PRODUCER (PRODUCER_CODE)^
create index IDX_CARSCUBAPLATFORM_AUTO_PRODUCER_ON_COUNTRY on CARSCUBAPLATFORM_AUTO_PRODUCER (COUNTRY_ID)^
-- end CARSCUBAPLATFORM_AUTO_PRODUCER
-- begin CARSCUBAPLATFORM_COLOR
create unique index IDX_CARSCUBAPLATFORM_COLOR_UNIQ_NAME on CARSCUBAPLATFORM_COLOR (NAME)^
-- end CARSCUBAPLATFORM_COLOR
-- begin CARSCUBAPLATFORM_AUTO_PICKING
alter table CARSCUBAPLATFORM_AUTO_PICKING add constraint FK_CARSCUBAPLATFORM_AUTO_PICKING_ON_CAR_BRAND foreign key (CAR_BRAND_ID) references CARSCUBAPLATFORM_CAR_BRAND(ID)^
create index IDX_CARSCUBAPLATFORM_AUTO_PICKING_ON_CAR_BRAND on CARSCUBAPLATFORM_AUTO_PICKING (CAR_BRAND_ID)^
-- end CARSCUBAPLATFORM_AUTO_PICKING
-- begin CARSCUBAPLATFORM_CAR_BRAND
alter table CARSCUBAPLATFORM_CAR_BRAND add constraint FK_CARSCUBAPLATFORM_CAR_BRAND_ON_AUTO_PRODUCER foreign key (AUTO_PRODUCER_ID) references CARSCUBAPLATFORM_AUTO_PRODUCER(ID)^
create index IDX_CARSCUBAPLATFORM_CAR_BRAND_ON_AUTO_PRODUCER on CARSCUBAPLATFORM_CAR_BRAND (AUTO_PRODUCER_ID)^
-- end CARSCUBAPLATFORM_CAR_BRAND
-- begin CARSCUBAPLATFORM_CAR
alter table CARSCUBAPLATFORM_CAR add constraint FK_CARSCUBAPLATFORM_CAR_ON_AUTO_PRODUCER foreign key (AUTO_PRODUCER_ID) references CARSCUBAPLATFORM_AUTO_PRODUCER(ID)^
alter table CARSCUBAPLATFORM_CAR add constraint FK_CARSCUBAPLATFORM_CAR_ON_CAR_BRAND foreign key (CAR_BRAND_ID) references CARSCUBAPLATFORM_CAR_BRAND(ID)^
alter table CARSCUBAPLATFORM_CAR add constraint FK_CARSCUBAPLATFORM_CAR_ON_AUTO_PICKING foreign key (AUTO_PICKING_ID) references CARSCUBAPLATFORM_AUTO_PICKING(ID)^
create index IDX_CARSCUBAPLATFORM_CAR_ON_AUTO_PRODUCER on CARSCUBAPLATFORM_CAR (AUTO_PRODUCER_ID)^
create index IDX_CARSCUBAPLATFORM_CAR_ON_CAR_BRAND on CARSCUBAPLATFORM_CAR (CAR_BRAND_ID)^
create index IDX_CARSCUBAPLATFORM_CAR_ON_AUTO_PICKING on CARSCUBAPLATFORM_CAR (AUTO_PICKING_ID)^
-- end CARSCUBAPLATFORM_CAR
-- begin CARSCUBAPLATFORM_AUTO_BUYING_REQUEST
alter table CARSCUBAPLATFORM_AUTO_BUYING_REQUEST add constraint FK_CARSCUBAPLATFORM_AUTO_BUYING_REQUEST_ON_CAR foreign key (CAR_ID) references CARSCUBAPLATFORM_CAR(ID)^
alter table CARSCUBAPLATFORM_AUTO_BUYING_REQUEST add constraint FK_CARSCUBAPLATFORM_AUTO_BUYING_REQUEST_ON_LEGAL_PERSONAL_INFO foreign key (LEGAL_PERSONAL_INFO_ID) references CARSCUBAPLATFORM_LEGAL_PERSONAL_INFO(ID)^
alter table CARSCUBAPLATFORM_AUTO_BUYING_REQUEST add constraint FK_CARSCUBAPLATFORM_AUTO_BUYING_REQUEST_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
create index IDX_CARSCUBAPLATFORM_AUTO_BUYING_REQUEST_ON_CAR on CARSCUBAPLATFORM_AUTO_BUYING_REQUEST (CAR_ID)^
create index IDX_CARSCUBAPLATFORM_AUTO_BUYING_REQUEST_ON_LEGAL_PERSONAL_INFO on CARSCUBAPLATFORM_AUTO_BUYING_REQUEST (LEGAL_PERSONAL_INFO_ID)^
create index IDX_CARSCUBAPLATFORM_AUTO_BUYING_REQUEST_ON_MANAGER on CARSCUBAPLATFORM_AUTO_BUYING_REQUEST (MANAGER_ID)^
-- end CARSCUBAPLATFORM_AUTO_BUYING_REQUEST
